config/routes.rb
Ipofs::Application.routes.draw do
  resources :thanas do
    collection do
      delete 'destroy_multiple'
    end
  end

  resources :pofficers do
    collection do
      delete 'destroy_multiple'
    end  
  end

  resources :natures do
    collection do
      delete 'destroy_multiple'
    end  
  end

  resources :districts do
    collection do
      delete 'destroy_multiple'
    end  
  end
  
  resources :natures do
    collection do
      delete 'destroy_multiple'
    end 
  end

  resources :case_files do
    collection do
      delete 'destroy_multiple'
    end 
  end
   
  root to: 'case_files#index'   

end

app/models/case_file.rb
class CaseFile < ActiveRecord::Base
  belongs_to :village 
  belongs_to :nature 
  belongs_to :thana
  has_many :relateds, dependent: :delete_all
  
  has_many :laws, dependent: :delete_all
  has_many :acts, through: :laws	

  has_many :passages, dependent: :delete_all
  has_many :sections, through: :passages

  attr_accessible :deo, :event, :file_date, :file_no, :file_time, :remark, :title, :address, :officer_name, :designation, :act_list, :section_list, :case_pdf, :case_pdf_cache, :remove_case_pdf, :thana_id, :nature_id, :village_id
  
  accepts_nested_attributes_for :relateds, :reject_if => lambda { |a| a[:name].blank? }, :allow_destroy => true  

  attr_accessible :relateds_attributes

  # File Upload
  mount_uploader :case_pdf, CaseUploader  

  def section_list
    self.sections.collect do |section|
      section.section_no
    end.join(", ")  
  end  

  def section_list=(section)
    section_no = section.split(",").collect {|s| s.strip.downcase}.uniq  
    new_or_found_sections = section_no.collect{ |num| Section.find_or_create_by_section_no(section_no: num)}
    self.sections = new_or_found_sections
  end  
  
  def act_list
    self.acts.collect do |act|
      act.act_name
    end.join(", ")  
  end  

  def act_list=(act)
    act_name = act.split(",").collect {|s| s.strip.downcase}.uniq  
    new_or_found_acts = act_name.collect{ |name| Act.find_or_create_by_act_name(act_name: name)}
    self.acts = new_or_found_acts
  end

  # Searching, sorting and filtering
  filterrific(
    default_filter_params: { sorted_by: 'created_at_desc'},
    available_filters: [
      :sorted_by,
      :search_query,
      :with_thana_name
    ]    
  )

  scope :search_query, lambda { |query|
    return nil if query.blank?

    # condition query, parse into individual keywords
    terms = query.to_s.downcase.split(/\s+/)

    # replace "*" with "%" for wildcard searches,
    # append '%', remove duplicate '%'s
    terms = terms.map { |e|
      ('%' + e.gsub('*', '%') + '%').gsub(/%+/, '%')
    }

    # configure number of OR conditions for provision
    # of interpolation arguments. Adjust this if you
    # change the number of OR conditions.
    num_or_conditions = 3
    where(
      terms.map {
        or_clauses = [
          "case_files.file_no LIKE ?",
          "case_files.title LIKE ?",
          "case_files.officer_name LIKE ?"
        ].join(' OR ')
          "(#{ or_clauses })"
      }.join(' AND '),
      *terms.map { |e| [e] * num_or_conditions }.flatten
    )
  }

  scope :sorted_by, lambda { |sort_option|
    # extract the sort direction from the param value.
      direction = (sort_option =~ /desc$/) ? 'desc' : 'asc'
      case sort_option.to_s
      when /^created_at_/
        # Simple sort on the created_at column.
        # Make sure to include the table name to avoid ambiguous column names.
        # Joining on other tables is quite common in Filterrific, and almost
        # every ActiveRecord table has a 'created_at' column.
        order("case_files.created_at #{ direction }")
      else
        raise(ArgumentError, "Invalid sort option: #{ sort_option.inspect }")
      end
  }

  def self.options_for_sorted_by
      [
        ['Case File date (newest first)', 'created_at_desc'],
        ['Case File date (oldest first)', 'created_at_asc']
      ]
  end

  scope :with_thana_name, lambda { |thana_name|
    where('thanas.name = ?', thana_name).joins(:thana)
  }  

end

app/controllers/case_files_controller.rb
class CaseFilesController < ApplicationController
  # GET /case_files
  # GET /case_files.json
  def index
      @filterrific = initialize_filterrific(
      CaseFile,
      params[:filterrific],
      select_options: {
        sorted_by: CaseFile.options_for_sorted_by,
        with_thana_name: Thana.pluck(:name)
      },
      persistence_id: 'shared_key',
      default_filter_params: { sorted_by: 'created_at_desc' },
      available_filters: [ 
        :sorted_by,
        :search_query,
        :with_thana_name ],
    ) or return

    @case_files = Kaminari.paginate_array(@filterrific.find).page(params[:page]).per(25)

    respond_to do |format|
      format.html # index.html.erb
      format.js {}
      format.json { render json: @case_files }
    end
  end

  # GET /case_files/1
  # GET /case_files/1.json
  def show
    @case_file = CaseFile.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @case_file }
    end
  end

  # GET /case_files/new
  # GET /case_files/new.json
  def new
    @case_file = CaseFile.new 
    @case_file.relateds.build
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @case_file }
    end
  end
  

  # GET /case_files/1/edit
  def edit
    @case_file = CaseFile.find(params[:id])
  end

  # POST /case_files
  # POST /case_files.json
  def create
    @case_file = CaseFile.new(params[:case_file])
     @case_file.relateds.build
    respond_to do |format|
      if @case_file.save
        format.html { redirect_to case_files_path, notice: 'Case file was successfully created.' }
        format.json { render json: @case_file, status: :created, location: @case_file }
      else
        format.html { render action: "new" }
        format.json { render json: @case_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /case_files/1
  # PUT /case_files/1.json
  def update
    @case_file = CaseFile.find(params[:id])

    respond_to do |format|
      if @case_file.update_attributes(params[:case_file])
        format.html { redirect_to case_files_path, notice: 'Case file was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @case_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /case_files/1
  # DELETE /case_files/1.json
  def destroy
    @case_file = CaseFile.find(params[:id])
    @case_file.destroy

    respond_to do |format|
      format.html { redirect_to case_files_url }
      format.json { head :no_content }
    end
  end


  def destroy_multiple
    if params[:case_files].nil?
      redirect_to case_files_path
    else  
      CaseFile.destroy(params[:case_files])

      respond_to do |format|
        format.html { redirect_to case_files_path }
        format.json { head :no_content }
      end
    end    
  end
  
end

    

app/helpers/case_files_helper.rb
module CaseFilesHelper
end

app/views/case_files/_form.html.erb
<%= nested_form_for(@case_file, :html => { :class => 'form-horizontal', :multipart => true}) do |f| %>
  <% if @case_file.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@case_file.errors.count, "error") %> prohibited this case_file from being saved:</h2>
      <ul>
      <% @case_file.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div role="tabpanel">
  <!-- Nav tabs -->
  <ul id="tabs" class="nav nav-pills custom" role="tablist">
    <li role="presentation" class="active"><a href="#detail1"  aria-controls="detail1" role="tab" data-toggle="tab">Incident Details</a></li>
    <li role="presentation"><a href="#detail2" aria-controls="detail2" role="tab" data-toggle="tab">Location Details</a></li>
    <li role="presentation"><a href="#detail3" aria-controls="detail3" role="tab" data-toggle="tab">Officer Details</a></li>
    <li role="presentation"><a href="#detail4" aria-controls="detail4" role="tab" data-toggle="tab">Related Person Details</a></li>
    <li role="presentation"><a href="#detail5" aria-controls="detail5" role="tab" data-toggle="tab">Upload PDF</a></li>
  </ul>

<!-- Tab panes -->
<div class="tab-content">
  <div role="tabpanel" class="panel panel-default tab-pane active" style="margin-top:10px" id="detail1">
    <div class="panel-heading">
        Incident Details
    </div>
    <div class="panel-body">  
      <fieldset>
        <div class="form-group">
          <span class="col-md-offset-1 col-md-3">
            <%= f.label :file_no, "File Number", :class => 'label-control' %>
          </span>
          <span class="col-md-6">  
            <%= f.text_field :file_no, :class => 'form-control' %>
          </span>  
        </div>
        <div class="form-group">
          <span class="col-md-offset-1 col-md-3">
            <%= f.label :title, :class => 'label-control' %>
          </span>
          <span class="col-md-6">
            <%= f.text_field :title, :class => 'form-control' %>
          </span>
        </div>
        <div class="form-group">
          <span class="col-md-offset-1 col-md-3">
            <%= f.label :file_date, "File Date", :class => 'label-control' %>
          </span>
          <span class="col-md-6">
            <%= f.text_field :file_date, :class => 'form-control datepicker' %>
            <p class="help-block"> Date Format: YYYY/MM/DD </p>
          </span>
        </div>
        <div class="form-group">
          <span class="col-md-offset-1 col-md-3">
            <%= f.label :file_time, "File Time", :class => 'label-control' %>
          </span>
          <span class="col-md-6">
            <%= f.time_select :file_time, :default => Time.now %>
          </span>
        </div>
        <div class="form-group">
          <span class="col-md-offset-1 col-md-3">
            <%= f.label :event, :class => 'label-control' %>
          </span>
          <span class="col-md-6">
            <%= f.text_field :event, :class => 'form-control' %>
          </span>
        </div>
        <div class="form-group">
          <span class="col-md-offset-1 col-md-3">
            <%= f.label :nature, :class => 'label-control' %>
          </span>
          <span class="col-md-6">
            <%= collection_select(:case_file, :nature_id, Nature.all, :id, :nature_desc, { :include_blank => "Select a Nature" }, { :class => 'form-control'}) %>
          </span>
        </div>
        <div class="form-group">
          <span class="col-md-offset-1 col-md-3">
            <%= f.label :act_list, "Acts", :class => 'label-control' %>
          </span>
          <span class="col-md-6">
            <%= f.text_field :act_list, :class => 'form-control' %>
          </span>
        </div>
        <div class="form-group">
          <span class="col-md-offset-1 col-md-3">
            <%= f.label :section_list, "Sections", :class => 'label-control' %>
          </span>
          <span class="col-md-6">
            <%= f.text_field :section_list, :class => 'form-control' %>
          </span>
        </div>
      </fieldset>
    </div>
    <!-- panel-body -->
    <div class="col-sm-offset-4 col-sm-8" style="margin-top:10px" >
      <span class="btn btn-xs btn-default" id="toggle1">Previous</span>
      <span class="btn btn-xs btn-default" id="toggle2">Next</span>
    </div>
    <!-- Prev-Next Button -->    
  </div>
  <!-- panel -->  

    <div role="tabpanel" class="panel panel-default tab-pane" style="margin-top:10px" id="detail2">
      <div class="panel-heading">
          Location Details
      </div>
      <div class="panel-body">    
        <div class="form-group">
          <span class="col-md-offset-1 col-md-3">
            <%= f.label :address, :class => 'label-control' %>
          </span>
          <span class="col-md-6">
            <%= f.text_area :address, :class => 'form-control', :style => 'height:100px' %>
          </span>
        </div>
        <div class="form-group">
          <span class="col-md-offset-1 col-md-3">
            <%= f.label :district, :class => 'label-control' %>
          </span>
          <span class="col-md-6">
            <%= collection_select(nil, :district_id, District.order(:name),  :id, :name, {:prompt   => "Select a District"}, {:id => 'districts_select', :class => 'form-control'}) %>
          </span>
        </div>  
        <div class="form-group">
          <span class="col-md-offset-1 col-md-3">
            <%= f.label :tehsil, :class => 'label-control' %>
          </span>
          <span class="col-md-6">
            <%= grouped_collection_select(nil, :tehsil_id, District.order(:name), :tehsils , :name, :id, :name, {:prompt   => "Select a Tehsil"}, {:id => 'tehsils_select', :class => 'form-control'}) %>
          </span>
        </div>
        <div class="form-group">  
          <span class="col-md-offset-1 col-md-3">
            <%= f.label :village, :class => 'label-control' %>
          </span>
          <span class="col-md-6">
            <%= grouped_collection_select(:case_file, :village_id, Tehsil.order(:name),:villages , :name, :id, :name, {:prompt   => "Select a Village"}, {:id => 'villages_select', :class => 'form-control'}) %>
          </span>
        </div>      
      </fieldset>
    </div>
    <!-- panel-body -->

    <div class="col-sm-offset-4 col-sm-8" style="margin-top:10px" >
      <span class="btn btn-xs btn-default" id="toggle3">Previous</span>
      <span class="btn btn-xs btn-default" id="toggle4">Next</span>
    </div>
    <!-- Prev-Next Button -->    
  </div>
  <!-- panel -->

  <div role="tabpanel" class="panel panel-default tab-pane" style="margin-top:10px" id="detail3">
    <div class="panel-heading">
        Officer Details
    </div>
    <div class="panel-body">  
      <fieldset>
        <div class="form-group">
          <span class="col-md-offset-1 col-md-3">
            <%= f.label :officer_name, "Police Officer", :class => 'label-control' %>
          </span>
          <span class="col-md-6">
            <%= f.text_field :officer_name, :class => 'form-control' %>
          </span>
        </div>
         <div class="form-group">
          <span class="col-md-offset-1 col-md-3">
            <%= f.label :designation, :class => 'label-control' %>
          </span>
          <span class="col-md-6">
            <%= f.text_field :designation, :class => 'form-control' %>
          </span>
        </div>
        <div class="form-group">
          <span class="col-md-offset-1 col-md-3">
            <%= f.label :deo, "Data Entry Operator", :class => 'label-control' %>
          </span>
          <span class="col-md-6">
            <%= f.text_field :deo, :class => 'form-control' %>
          </span>
        </div>
        <div class="form-group">
          <span class="col-md-offset-1 col-md-3">
            <%= f.label :thana, :class => 'label-control' %>
          </span>
          <span class="col-md-6">
            <%= collection_select(:case_file, :thana_id, Thana.all, :id, :name, { :include_blank => "Select a Thana" }, { :class => 'form-control'}) %>
          </span>
        </div>
      </fieldset>
    </div>
    <!-- panel-body -->

    <div class="col-sm-offset-4 col-sm-8" style="margin-top:10px" >
      <span class="btn btn-xs btn-default" id="toggle5">Previous</span>
      <span class="btn btn-xs btn-default" id="toggle6">Next</span>
    </div>
    <!-- Prev-Next Button -->
  </div>
  <!-- panel -->

  <div role="tabpanel" class="panel panel-default tab-pane" style="margin-top:10px" id="detail4">
    <div class="panel-heading">
        Related Person Details
    </div>
    <div class="panel-body">
        <%= f.fields_for :relateds do |builder| %>
          <%= render "related_fields", :f => builder %>
        <% end %>
        <%= f.link_to_add "Add Related Person", :relateds, {:class => 'btn btn-xs btn-default'} %>
    </div>
    <!-- panel-body -->
    
    <div class="col-sm-offset-4 col-sm-8" style="margin-top:10px" >
      <span class="btn btn-xs btn-default" id="toggle7">Previous</span>
      <span class="btn btn-xs btn-default" id="toggle8">Next</span>
    </div>
    <!-- Prev-Next Button -->
  </div>
  <!-- panel -->

  <div role="tabpanel" class="panel panel-default tab-pane" style="margin-top:10px" id="detail5">
    <div class="panel-heading">
        Upload PDF
    </div>
    <div class="panel-body">  
      <fieldset>
        <div class="form-group">
          <span class="col-md-offset-1 col-md-3">
            <%= f.label :remark, :class => 'label-control' %>
          </span>
          <span class="col-md-6">
            <%= f.text_area :remark, :class => 'form-control', :style => 'height:100px' %>
          </span>
        </div>
        <div class="form-group">
          <span class="col-md-offset-1 col-md-3">
            <%= f.label :case_pdf, "Upload Case File", :class => 'label-control' %>
          </span>
          <span class="col-md-6">
            <% if @case_file.case_pdf? %>
              <%= link_to image_tag('/assets/pdf.png'), @case_file.case_pdf.url, target: '_blank' %><br/>
              <%= f.check_box :remove_case_pdf %>
            <% else %>   
              <%= f.file_field :case_pdf, :required => true %>
              <%= f.hidden_field :case_pdf_cache %>
            <% end %>
          </span>  
        </div>
      </fieldset>
    </div>
    <!-- panel-body-->

    <div class="col-sm-offset-4 col-sm-8" style="margin-top:10px" >
      <span class="btn btn-xs btn-default" id="toggle9">Previous</span>
      <span class="btn btn-xs btn-default" id="toggle10">Next</span>
    </div>
    <!-- Prev-Next Button -->

    <div class="col-sm-offset-4 col-sm-8" style="margin-top:20px">
        <%= f.submit "Submit", :class => 'btn btn-primary btn-md' %>
        <%= link_to 'Back', case_files_path, :class => 'btn btn-default btn-sm' %>
    </div>
  </div>
  <!-- panel-->
</div>
<!-- Tab Content-->
</div>
<!-- Tab Panel -->

<% end %>

app/views/case_files/_list.html.erb
  <div class="panel panel-default">
    <div class="panel-body">
        <table class="table table-striped table-hover">
          <tr>
            <th></th>
            <th>S.no</th>
            <th>Case File no.</th>
            <th>Title</th>
            <th>File Date</th>
            <th>Address</th>
            <th>Event</th>
            <th>Thana</th>
            <th>Police Officer</th>
            <th></th>
            <th></th>
            <th></th>
          </tr>
          <% i=0 %>
          <% @case_files.each do |case_file| %>
            <tr>
              <td><%= check_box_tag "case_files[]", case_file.id %></td>
              <td><%= p i=i+1 %></td>
              <td><%= case_file.file_no %></td>
              <td><%= case_file.title %></td>
              <td><%= case_file.file_date.strftime('%d-%m-%Y') %></td>
              <td><%= case_file.address %></td>
              <td><%= case_file.event %></td>
              <td><%= case_file.thana.name %></td>
              <td><%= case_file.officer_name %></td>
              <td><%= link_to "View", case_file, :class => 'btn btn-xs btn-default' %></td>
              <td><%= link_to "Edit", edit_case_file_path(case_file), :class => 'btn btn-xs btn-default' %></td>
              <% if case_file.case_pdf? %>
                <td><%= link_to image_tag('/assets/pdf.png')+"Download", case_file.case_pdf.url, target: '_blank' %></td>
              <% else %>
                <td>N/A</td>
              <% end %>    
            </tr>
          <% end %>  
        </table>
        <%= paginate @case_files %> 
    </div>
  </div>  

app/views/case_files/_related_fields.html.erb
<div class="form-group">
	<span class="col-md-offset-1 col-md-3">
	  <%= f.label :name, "Related Person", :class => 'label-control' %>
	</span>
	<span class="col-md-6">
	  <%= f.text_field :name, :class => 'form-control' %>
	</span>
</div>
<div class="form-group">
	<span class="col-md-offset-1 col-md-3">
	  <%= f.label :relation, :class => 'label-control' %>
	</span>
	<span class="col-md-6">
	  <%= f.text_field :relation, :class => 'form-control' %>
	</span>
</div>
<div class="form-group">
	<span class="col-md-offset-1 col-md-3">
	  <%= f.label :address, :class => 'label-control' %>
	</span>
	<span class="col-md-6">
	  <%= f.text_field :address, :class => 'form-control' %>
	</span>
</div>
<div class="form-group">	
	<span class="col-md-offset-1 col-md-3">
	  <%= f.label :contact, :class => 'label-control' %>
	</span>
	<span class="col-md-6">
	  <%= f.text_field :contact, :class => 'form-control' %>
	</span>
</div>
<div class="form-group">	
	<span class="col-md-offset-1 col-md-3">
	  <%= f.label :guardian_name, "Guardian Name", :class => 'label-control' %>
	</span>
	<span class="col-md-6">
	  <%= f.text_field :guardian_name, :class => 'form-control' %>
	</span>
</div>	
<div class="form-group">	
	<span class="col-md-offset-1 col-md-3">
	  <%= f.label :remark, :class => 'label-control' %>
	</span>
	<span class="col-md-6">
	  <%= f.text_field :remark, :class => 'form-control' %>
	</span>
</div>
	<%= f.link_to_remove "Remove", {:class => 'btn btn-xs btn-default'} %>
<hr>

app/views/case_files/edit.html.erb
<!-- row -->
<div class="row">
	<div class="text-center">	
		<h1 class="page-header text-muted">Edit Case File</h1>
	</div>
</div>
<!-- /.row -->		

<!-- row -->
<div class="row"> 		
		<div class="col-lg-offset-2 col-lg-8 col-lg-offset-2 "> 
			<%= render 'form' %>
		</div>
		<!-- col-lg-offset-->	
</div>	
<!-- /.row-->

app/views/case_files/index.html.erb
<!-- row -->
<div class="row">
  <div class="text-center">
    <h1 class="page-header text-muted">List Of Case Files</h1>
  </div>
</div>
<!-- /.row -->

<div class="well">
    <%= form_for_filterrific @filterrific do |f| %>
      <div class="col-md-1">
        <label class="label-control"> Search:</label>
      </div>
      <div class="col-md-3">
        <%# give the search field the 'filterrific-periodically-observed' class for live updates %>
        <%= f.text_field(
          :search_query,
          class: 'filterrific-periodically-observed form-control', placeholder: 'Enter Search keyword'
        ) %>
      </div>
      <div class="col-md-1">
        <label class="label-control"> Filter:</label>
      </div>
      <div class="col-md-3">
        <%= f.select(:with_thana_name, @filterrific.select_options[:with_thana_name], { include_blank: 'Select a Thana' }, { :class => 'filterrific-periodically-observed form-control'}) %>
      </div>
      <div class="col-md-1">
        <label class="label-control"> Sort By:</label>
      </div>
      <div class="col-md-3">  
        <%= f.select(:sorted_by, @filterrific.select_options[:sorted_by], { include_blank: 'Sort By:' }, { :class => 'filterrific-periodically-observed form-control'}) %>
      </div>
      <br/>
      <br/>
      <br/>
      <%= link_to 'Reset filters', reset_filterrific_url, :class => 'btn btn-sm btn-default' %>
      <%# add an automated spinner to your form when the list is refreshed %>
      <%= render_filterrific_spinner %>
    <% end %>
</div>
<!-- /.well -->

<%= form_tag destroy_multiple_case_files_path, method: :delete do %>
<!-- row -->
<div class="row">
  <div class="col-md-offset-1 col-md-11" id="filterrific_results">
    <%= render(
        partial: 'case_files/list',
        locals: { case_files: @case_files }
      ) %>
  </div>
</div>
<!-- /.row -->
              
<span class="col-md-offset-5 col-md-1">
    <%= submit_tag "Delete selected", :class => 'btn btn-default', data: { confirm: "Are You sure?" } %>
</span>
<% end %>

app/views/case_files/index.js.erb
<% js = escape_javascript(
  render(partial: 'case_files/list', locals: { case_files: @case_files })
) %>
$("#filterrific_results").html("<%= js %>");

app/views/case_files/new.html.erb
<!-- row -->
<div class="row">
	<div class="text-center">	
		<h1 class="page-header text-muted">New Case File</h1>
	</div>
</div>
<!-- /.row -->		

<!-- row -->
<div class="row"> 		
		<div class="col-lg-offset-2 col-lg-8  "> 
			<%= render 'form' %>
		</div>
		<!-- col-lg-offset-->	
</div>	
<!-- /.row-->

app/views/case_files/show.html.erb
<!-- row -->            
<div class="row">
    <div class="col-lg-12">
    	<div class="text-center">
        	<h1 class="page-header text-muted">Case File Detail</h1>
    	</div>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->

<!-- row -->
<div class="row">
	<div class="col-md-offset-1 col-md-10 col-md-offset-1">
		<div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title">#<%= @case_file.file_no %> <%= @case_file.title %></h3>
            </div>
            <div class="panel-body">
              <div class="row">
                <div class="col-md-3 col-lg-3 " align="center"> 
                	<% if @case_file.case_pdf? %>
                		<%= link_to image_tag('/assets/pdf-icon.png'), @case_file.case_pdf.url, target: '_blank' %>
              		<% else %>
                		N/A
              		<% end %>     
          		</div>
                
                <div class=" col-md-9 col-lg-9 "> 
                  <table class="table table-user-information">
                    <tbody>
                      <tr>
                        <td><b>Case File Date</b></td>
                        <td><%= @case_file.file_date.strftime('%d-%m-%Y') %></td>
                      </tr>  
                      <tr>
                        <th>Case File Time</th>
                        <td><%= @case_file.file_time.strftime("%H:%M") %></td>
                      </tr>
                      <tr>
                        <th>Event</th>
                        <td><%= @case_file.event %></td>
                      </tr>
                      <tr>
                        <th>Nature</th>
                        <td><%= @case_file.nature.nature_desc %></td>
                      </tr>
                      <tr>
                        <th>Acts</th>
                        <td>
                          <%= @case_file.acts.collect {|act| act.act_name }.to_sentence(words_connector: ', ', last_word_connector: ', ') %>           
                        </td>  
                      </tr>
                      <tr>
                        <th>Sections</th>
                        <td>
                          <%= @case_file.sections.collect {|section| section.section_no }.to_sentence(words_connector: ', ', last_word_connector: ', ') %>           
                        </td>  
                      </tr>
                      <tr>
                        <th>Thana</th>
                        <td><%= @case_file.thana.name %></td>
                      </tr>
                      <tr>
                        <th>Police Officer</th>
                        <td><%= @case_file.officer_name %></td>
                      </tr>
                      <tr>
                        <th>Designation</th>
                        <td><%= @case_file.designation %></td>
                      </tr>
                      <tr>
                        <th>Data Entry Operator</th>
                        <td><%= @case_file.deo %></td>
                      </tr> 
                      <tr>
                        <th>Remark</th>
                        <td><%= @case_file.remark %></td>
                      </tr>
                      <tr>
                        <td>&nbsp;</td>
                      </tr>
                      <tr>
                        <th>Address</th>
                        <td><%= @case_file.address %></td>
                      </tr>
                      <tr>
                        <th>Village</th>
                        <td><%= @case_file.village.name  %></td>
                      </tr>
                      <tr>
                        <th>Tehsil</th>
                        <td><%= @case_file.village.tehsil.name  %></td>
                      </tr>
                      <tr>
                        <th>District</th>
                        <td><%= @case_file.village.tehsil.district.name %></td>
                      </tr>
                      <tr>
                        <td>&nbsp;</td>
                      </tr> 
                      <% @case_file.relateds.each do |related| %>  
                        <tr>
                          <th>Person name</th>
                          <td><%= related.name %></td>
                        </tr>
                        <tr>
                          <th>Relation</th>
                          <td><%= related.relation %></td>
                        </tr>
                        <tr>
                          <th>Address</th>
                          <td><%= related.address %></td>
                        </tr>
                        <tr>
                          <th>Contact</th>
                          <td><%= related.contact %></td>
                        </tr>
                        <tr>
                          <td>&nbsp;</td>
                        </tr>
                      <% end %>                                
                    </tbody>
                  </table>
                </div>
                <!-- /. col-md-9 -->
              </div>
              <!-- /. row -->
        </div>
        <!-- /. panel body -->

    </div>
    <!-- /. panel -->
	</div>
	<!-- col-md-10 -->
<span class="col-md-offset-5 col-md-1">
    <%= link_to "Back", case_files_path, :class => 'btn btn-default' %>
</span>	
</div>
<!-- /.row -->	

app/views/case_files/update_tehsils.js.erb
# app/views/home/update_tehsils.js.erb
$('#tehsils_select').html("<%= escape_javascript(options_for_select(@tehsils)) %>");
$('#villages_select').html("<%= escape_javascript(options_for_select(@villages)) %>");
 

app/views/case_files/update_villages.js.erb
# app/views/home/update_villages.js.erb
$('#villages_select').html("<%= escape_javascript(options_for_select(@villages)) %>");