config/routes.rb
Ipofs::Application.routes.draw do
  resources :thanas do
    collection do
      delete 'destroy_multiple'
    end
  end

  resources :pofficers do
    collection do
      delete 'destroy_multiple'
    end  
  end

  resources :natures do
    collection do
      delete 'destroy_multiple'
    end  
  end

  resources :districts do
    collection do
      delete 'destroy_multiple'
    end  
  end
  
  resources :natures do
    collection do
      delete 'destroy_multiple'
    end 
  end

  resources :case_files do
    collection do
      delete 'destroy_multiple'
    end 
  end
   
  root to: 'case_files#index'   

end

app/models/nature.rb
class Nature < ActiveRecord::Base
	has_many :case_files, dependent: :delete_all 
  	attr_accessible :nature_desc, :nature_id
  	attr_accessible :case_files_attributes
end

app/controllers/natures_controller.rb
class NaturesController < ApplicationController
  # GET /natures
  # GET /natures.json
  def index
    @natures = Nature.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @natures }
    end
  end

  # GET /natures/1
  # GET /natures/1.json
  def show
    redirect_to natures_path
  end

  # GET /natures/new
  # GET /natures/new.json
  def new
    @nature = Nature.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @nature }
    end
  end

  # GET /natures/1/edit
  def edit
    @nature = Nature.find(params[:id])
  end

  # POST /natures
  # POST /natures.json
  def create
    @nature = Nature.new(params[:nature])

    respond_to do |format|
      if @nature.save
        format.html { redirect_to natures_path, notice: 'Nature was successfully created.' }
        format.json { render json: @nature, status: :created, location: @nature }
      else
        format.html { render action: "new" }
        format.json { render json: @nature.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /natures/1
  # PUT /natures/1.json
  def update
    @nature = Nature.find(params[:id])

    respond_to do |format|
      if @nature.update_attributes(params[:nature])
        format.html { redirect_to natures_path, notice: 'Nature was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @nature.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /natures/1
  # DELETE /natures/1.json
  def destroy
    @nature = Nature.find(params[:id])
    @nature.destroy

    respond_to do |format|
      format.html { redirect_to natures_url }
      format.json { head :no_content }
    end
  end

  def destroy_multiple
    if params[:natures].nil?
      redirect_to natures_path
    else    
      Nature.destroy(params[:natures])
      respond_to do |format|
        format.html { redirect_to natures_path}
        format.json { head :no_content }
      end
    end
  end

end

app/helpers/natures_helper.rb
module NaturesHelper
end

app/views/natures/_form.html.erb
<%= form_for(@nature, :html => { :class => 'form-horizontal', :multipart => true}) do |f| %>
  <% if @nature.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@nature.errors.count, "error") %> prohibited this nature from being saved:</h2>

      <ul>
      <% @nature.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <fieldset>
    <div class="form-group">
      <span class="col-md-3">
        <%= f.label :nature_desc, "Nature Description", :class => 'label-control' %>
      </span>
      <span class="col-md-9">  
        <%= f.text_field :nature_desc, :class => 'form-control' %>
      </span>  
    </div>
    <div class="form-group">
      <span class="col-md-offset-4 col-md-6">
        <%= f.submit "Submit", :class => 'btn btn-primary' %>
        <%= link_to 'Back', natures_path, :class => 'btn btn-default' %>
      </span>
    </div>
  </fieldset>
<% end %>

app/views/natures/edit.html.erb
<!-- row -->
<div class="row">
	<div class="text-center">
		<h1 class="page-header text-muted">Edit Nature Details</h1>
	</div>	
</div>
<!-- /.row -->

<!-- row -->
<div class="row"> 		
		<div class="col-lg-offset-3 col-lg-6 col-lg-offset-3 ">
			<div class="panel panel-default">
				<div class="panel-heading">
					Please Fill Up the following
				</div> 
				<div class="panel-body">	
					<%= render 'form' %>
				</div>	
			</div>
			<!-- panel -->		
		</div>
		<!-- col-lg-offset-->	
</div>	
<!-- /.row-->

app/views/natures/index.html.erb
<!-- row -->
<div class="row">
  <div class="text-center">
    <h1 class="page-header text-muted">List Of Natures</h1>
  </div>
</div>
<!-- /.row -->

<%= form_tag destroy_multiple_natures_path, method: :delete do %>
<!-- row -->
<div class="row">
  <div class="col-md-offset-4 col-md-4 panel panel-default">
    <div class="panel-body">
      <table class="table table-striped table-hover">
        <tr>
          <th></th>
          <th>S.no</th>
          <th>Description of Nature</th>
          <th></th>
        </tr>
        <% i=0 %>
        <% @natures.each do |nature| %>
          <tr>
            <td><%= check_box_tag "natures[]", nature.id %></td>
            <td><%= p i=i+1 %></td>
            <td><%= nature.nature_desc %></td>
            <td><%= link_to "Edit", edit_nature_path(nature), :class => 'btn btn-xs btn-default' %></td>
          </tr>
        <% end %>  
      </table>
    </div>  
  </div>
</div>
<!-- /.row -->

<span class="col-md-offset-4 col-md-1">  
    <%= link_to 'New Nature', new_nature_path, :class => 'btn btn-default' %>
</span>    
<span class="col-md-offset-1 col-md-1">
    <%= submit_tag "Delete selected", :class => 'btn btn-default', data: { confirm: "Are You sure?" } %>
</span>
<% end %>

app/views/natures/new.html.erb
<!-- row -->
<div class="row">
	<div class="text-center">
		<h1 class="page-header text-muted">New Nature Details</h1>
	</div>	
</div>
<!-- /.row -->

<div class="row"> 		
		<div class="col-lg-offset-3 col-lg-6 col-lg-offset-3 ">
			<div class="panel panel-default">
				<div class="panel-heading">
					Please Fill Up the following
				</div> 
				<div class="panel-body">	
					<%= render 'form' %>
				</div>	
			</div>
			<!-- panel -->		
		</div>
		<!-- col-lg-offset-->	
</div>	
<!-- /.row-->