config/routes.rb
Ipofs::Application.routes.draw do
  resources :thanas do
    collection do
      delete 'destroy_multiple'
    end
  end

  resources :pofficers do
    collection do
      delete 'destroy_multiple'
    end  
  end

  resources :natures do
    collection do
      delete 'destroy_multiple'
    end  
  end

  resources :districts do
    collection do
      delete 'destroy_multiple'
    end  
  end
  
  resources :natures do
    collection do
      delete 'destroy_multiple'
    end 
  end

  resources :case_files do
    collection do
      delete 'destroy_multiple'
    end 
  end
   
  root to: 'case_files#index'   

end

app/models/thana.rb
class Thana < ActiveRecord::Base
	has_many :case_files, dependent: :delete_all
	attr_accessible :name, :address

	# Following fields must not remain blank
	validates :name, :address, presence: true

end

app/controllers/thanas_controller.rb
class ThanasController < ApplicationController
  # GET /thanas
  # GET /thanas.json
  def index
    @thanas = Thana.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @thanas }
    end
  end

  # GET /thanas/1
  # GET /thanas/1.json
  def show
    respond_to do |format|
      format.html { redirect_to thanas_path}# show.html.erb
    end
  end

  # GET /thanas/new
  # GET /thanas/new.json
  def new
    @thana = Thana.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @thana }
    end
  end

  # GET /thanas/1/edit
  def edit
    @thana = Thana.find(params[:id])
  end

  # POST /thanas
  # POST /thanas.json
  def create
    @thana = Thana.new(params[:thana])

    respond_to do |format|
      if @thana.save
        format.html { redirect_to thanas_path, notice: 'Thana was successfully created.' }
        format.json { render json: @thana, status: :created, location: @thana }
      else
        format.html { render action: "new" }
        format.json { render json: @thana.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /thanas/1
  # PUT /thanas/1.json
  def update
    @thana = Thana.find(params[:id])

    respond_to do |format|
      if @thana.update_attributes(params[:thana])
        format.html { redirect_to thanas_path, notice: 'Thana was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @thana.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /thanas/1
  # DELETE /thanas/1.json
  def destroy
    @thana = Thana.find(params[:id])
    @thana.destroy

    respond_to do |format|
      format.html { redirect_to thanas_url }
      format.json { head :no_content }
    end
  end

  def destroy_multiple
    if params[:thanas].nil?
      redirect_to thanas_path
    else  
      Thana.destroy(params[:thanas])
      respond_to do |format|
        format.html { redirect_to thanas_path }
        format.json { head :no_content }
      end
    end  
  end
  
end

app/helpers/thanas_helper.rb
module ThanasHelper
end

app/views/thanas/_form.html.erb
<%= form_for(@thana, :html => { :class => 'form-horizontal', :multipart => true}) do |f| %>
  <% if @thana.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@thana.errors.count, "error") %> prohibited this thana from being saved:</h2>

      <ul>
      <% @thana.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <fieldset>
    <div class="form-group">
      <span class="col-md-3">
        <%= f.label :name, "Name of Thana", :class => 'label-control' %>
      </span>
      <span class="col-md-9">  
        <%= f.text_field :name, :class => 'form-control' %>
      </span>  
    </div>
    <div class="form-group">
      <span class="col-md-3">
        <%= f.label :address, "Address Of Thana", :class => 'label-control' %>
      </span>
      <span class="col-md-9">
        <%= f.text_field :address, :class => 'form-control' %>
      </span>
    </div>  
    <div class="form-group">
      <span class="col-md-offset-4 col-md-6">
        <%= f.submit "Submit", :class => 'btn btn-primary' %>
        <%= link_to 'Back', thanas_path, :class => 'btn btn-default' %>
      </span>
    </div>
  </fieldset> 
<% end %>

app/views/thanas/edit.html.erb
<!-- row -->
<div class="row">
	<div class="text-center">
		<h1 class="page-header text-muted">Edit Thana Details</h1>
	</div>
</div>
<!-- /.row -->

<!-- row -->
<div class="row"> 		
		<div class="col-lg-offset-3 col-lg-6 col-lg-offset-3 ">
			<div class="panel panel-default">
				<div class="panel-heading">
					Please Fill Up the following
				</div> 
				<div class="panel-body">	
					<%= render 'form' %>
				</div>	
			</div>
			<!-- panel -->		
		</div>
		<!-- col-lg-offset-->	
</div>	
<!-- /.row-->

app/views/thanas/index.html.erb
<!-- row -->
<div class="row">
  <div class="text-center">
    <h1 class="page-header text-muted">List Of Thanas</h1>
  </div>
</div>
<!-- /.row -->

<%= form_tag destroy_multiple_thanas_path, method: :delete do %>
<!-- row -->
<div class="row">
  <div class="col-md-offset-3 col-md-6 panel panel-default">
    <div class="panel-body">
      <table class="table table-striped table-hover">
        <tr>
          <th></th>
          <th>S.no</th>
          <th>Name Of Thana</th>
          <th>Address Of Thana</th>
          <th></th>
        </tr>
          <% i=0 %>
          <% @thanas.each do |thana| %>
          <tr>
            <td><%= check_box_tag "thanas[]", thana.id %></td>
            <td><%= p i=i+1 %></td>
            <td><%= thana.name %></td>
            <td><%= thana.address %></td>
            <td><%= link_to "Edit", edit_thana_path(thana), :class => 'btn btn-xs btn-default' %></td>
          </tr>
          <% end %>  
      </table>
    </div>  
  </div>
</div>
<!-- /.row -->
<span class="col-md-offset-4 col-md-1">  
    <%= link_to 'New Thana', new_thana_path, :class => 'btn btn-default' %>
</span>    
<span class="col-md-offset-1 col-md-1">
<%= submit_tag "Delete selected", :class => 'btn btn-default', data: { confirm: "Are You sure?" } %>
</span>
<% end %>

app/views/thanas/new.html.erb
<!-- row -->
<div class="row">
	<div class="text-center">
		<h1 class="page-header text-muted">New Thana Details</h1>
	</div>
</div>
<!-- /.row -->

<!-- row -->
<div class="row"> 		
		<div class="col-lg-offset-3 col-lg-6 col-lg-offset-3 ">
			<div class="panel panel-default">
				<div class="panel-heading">
					Please Fill Up the following
				</div> 
				<div class="panel-body">	
					<%= render 'form' %>
				</div>	
			</div>
			<!-- panel -->		
		</div>
		<!-- col-lg-offset-->	
</div>	
<!-- /.row-->