config/routes.rb
Ipofs::Application.routes.draw do
  resources :thanas do
    collection do
      delete 'destroy_multiple'
    end
  end

  resources :pofficers do
    collection do
      delete 'destroy_multiple'
    end  
  end

  resources :natures do
    collection do
      delete 'destroy_multiple'
    end  
  end

  resources :districts do
    collection do
      delete 'destroy_multiple'
    end  
  end
  
  resources :natures do
    collection do
      delete 'destroy_multiple'
    end 
  end

  resources :case_files do
    collection do
      delete 'destroy_multiple'
    end 
  end
   
  root to: 'case_files#index'   

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="description" content="">
		<meta name="author" content="">			
		
		<title>IPOFS</title>

		<%= stylesheet_link_tag    "application", :media => "all" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
</head>
<body>
	<!-- Navigation -->
	<nav class="navbar">
			<!-- Container-fluid -->
			<div class="container-fluid">
				<!-- navbar-header -->
				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        			<span class="sr-only">Toggle navigation</span>
        			<span class="icon-bar"></span>
        			<span class="icon-bar"></span>
        			<span class="icon-bar"></span>
      				</button>
					<a class="navbar-brand" href="/">
						IPOFS
					</a>
				</div>
				<!-- /.navbar-header -->
				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">	
					<ul class="nav navbar-nav">
						<li class="<%= 'active' if current_page?(case_files_path) %>">
							<a href="/case_files">Home</a>
						</li>
						<li class="<%= 'active' if current_page?(new_case_file_path) %>">
							<a href="/case_files/new">New Case</a>
						</li>
	    				<li class="<%= 'active' if current_page?(districts_path) %>">
	    					<a href="/districts">Location Details</a>
	    				</li>
	    				<li class="<%= 'active' if current_page?(natures_path) %>">
							<a href="/natures">Nature</a>
						</li>
	    				<li class="<%= 'active' if current_page?(thanas_path) %>">
							<a href="/thanas">Thana</a>
						</li>    				
					</ul>
				</div>
				<!-- /.navbar-collapse -->	
			</div>
			<!-- /.Container -->
	</nav>
	<!-- /.Navigation -->

<div class="container">
	<%= yield %>
</div>
<hr>
<footer class="container">
    	<p>Copyright &copy; All Rights Reserved</p> 
</footer>	
</body>
</html>